name: Deploy to NuWebspace

on:
  push:
    branches:
      - main  # Replace with your target branch(es)

jobs:
  execute-script:
    if: false #Remove this line to enable
    runs-on: ubuntu-latest  # The runner environment

    steps:
      - name: Install Expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your repository code

      - name: Setup SSH script permissions
        run: chmod +x ./setup-ssh.sh  # Make your script executable

      - name: Run SSH Shell Script
        env:
            NUSPACE_USR: ${{ secrets.NUSPACE_USR }}
            NUSPACE_PWD: ${{ secrets.NUSPACE_PWD }}
        run: ./setup-ssh.sh  # Executes your script

      - name: Set Execute Permission
        run: chmod +x ./deploy.sh  # Make your script executable

      - name: Run Shell Script
        env:
            NUSPACE_USR: ${{ secrets.NUSPACE_USR }}
            NUSPACE_PWD: ${{ secrets.NUSPACE_PWD }}
        run: ./deploy.sh  # Executes your script
